/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

/**
 *
 * @author DLCH
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        loginUsernameInput = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        loginPasswordInput = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        loginConfirmButton = new javax.swing.JButton();
        switchToRegisterButton = new javax.swing.JButton();
        registerPanel = new javax.swing.JPanel();
        registerPanel.setVisible(false);
        registerLabel = new javax.swing.JLabel();
        registerUsernameInput = new javax.swing.JTextField();
        registerUsernameLabel = new javax.swing.JLabel();
        registerPasswordInput = new javax.swing.JPasswordField();
        registerPasswordLabel = new javax.swing.JLabel();
        registerPasswordConfirmInput = new javax.swing.JPasswordField();
        registerPasswordConfirmLabel = new javax.swing.JLabel();
        registerConfirmButton = new javax.swing.JButton();
        switchToLoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        loginPanel.setBackground(new java.awt.Color(0, 204, 204));

        loginLabel.setBackground(null);
        loginLabel.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");

        loginUsernameInput.setBackground(new java.awt.Color(255, 255, 255));
        loginUsernameInput.setForeground(new java.awt.Color(0, 0, 0));
        loginUsernameInput.setToolTipText("");
        loginUsernameInput.setBorder(null);
        loginUsernameInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        loginUsernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameInputActionPerformed(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setLabelFor(loginUsernameInput);
        usernameLabel.setText("Username: ");

        loginPasswordInput.setBackground(new java.awt.Color(255, 255, 255));
        loginPasswordInput.setForeground(new java.awt.Color(0, 0, 0));
        loginPasswordInput.setBorder(null);

        passwordLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setLabelFor(loginPasswordInput);
        passwordLabel.setText("Password:");

        loginConfirmButton.setBackground(new java.awt.Color(0, 0, 0));
        loginConfirmButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        loginConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        loginConfirmButton.setText("Confirm");
        loginConfirmButton.setBorder(null);
        loginConfirmButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginConfirmButton.setFocusPainted(false);
        loginConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginConfirmButtonActionPerformed(evt);
            }
        });

        switchToRegisterButton.setBackground(new java.awt.Color(0, 102, 102));
        switchToRegisterButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        switchToRegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        switchToRegisterButton.setText("Register");
        switchToRegisterButton.setBorder(null);
        switchToRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchToRegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginPanelLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel)
                            .addComponent(loginUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginPasswordInput)
                            .addComponent(passwordLabel)
                            .addComponent(loginConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(switchToRegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLabel)
                .addGap(1, 1, 1)
                .addComponent(loginUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(loginConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(switchToRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        registerPanel.setBackground(new java.awt.Color(0, 204, 204));

        registerLabel.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerLabel.setText("Register");

        registerUsernameInput.setBackground(new java.awt.Color(255, 255, 255));
        registerUsernameInput.setForeground(new java.awt.Color(0, 0, 0));
        registerUsernameInput.setBorder(null);

        registerUsernameLabel.setBackground(null);
        registerUsernameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        registerUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerUsernameLabel.setLabelFor(registerUsernameInput);
        registerUsernameLabel.setText("Username:");

        registerPasswordInput.setBackground(new java.awt.Color(255, 255, 255));
        registerPasswordInput.setForeground(new java.awt.Color(0, 0, 0));
        registerPasswordInput.setBorder(null);

        registerPasswordLabel.setBackground(null);
        registerPasswordLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        registerPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerPasswordLabel.setLabelFor(registerPasswordInput);
        registerPasswordLabel.setText("Password:");

        registerPasswordConfirmInput.setBackground(java.awt.Color.white);
        registerPasswordConfirmInput.setForeground(new java.awt.Color(0, 0, 0));
        registerPasswordConfirmInput.setToolTipText("");
        registerPasswordConfirmInput.setBorder(null);
        registerPasswordConfirmInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPasswordConfirmInputActionPerformed(evt);
            }
        });

        registerPasswordConfirmLabel.setBackground(null);
        registerPasswordConfirmLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        registerPasswordConfirmLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerPasswordConfirmLabel.setLabelFor(registerPasswordConfirmInput);
        registerPasswordConfirmLabel.setText("Password confirmation:");

        registerConfirmButton.setBackground(new java.awt.Color(0, 0, 0));
        registerConfirmButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        registerConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        registerConfirmButton.setText("Confirm");
        registerConfirmButton.setBorder(null);
        registerConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerConfirmButtonActionPerformed(evt);
            }
        });

        switchToLoginButton.setBackground(new java.awt.Color(0, 102, 102));
        switchToLoginButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        switchToLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        switchToLoginButton.setText("Back to login");
        switchToLoginButton.setBorder(null);
        switchToLoginButton.setFocusPainted(false);
        switchToLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchToLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(registerLabel))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registerUsernameInput)
                            .addComponent(registerUsernameLabel)
                            .addComponent(registerPasswordLabel)
                            .addComponent(registerPasswordInput)
                            .addComponent(registerPasswordConfirmLabel)
                            .addComponent(registerPasswordConfirmInput)
                            .addComponent(registerConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(switchToLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(registerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerPasswordConfirmLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerPasswordConfirmInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(switchToLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerPasswordConfirmInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPasswordConfirmInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerPasswordConfirmInputActionPerformed

    private void registerConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerConfirmButtonActionPerformed
        if (evt.getSource()==registerConfirmButton) {
            registerPanel.setVisible(false);
        }
    }//GEN-LAST:event_registerConfirmButtonActionPerformed

    private void loginConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginConfirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginConfirmButtonActionPerformed

    private void loginUsernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameInputActionPerformed

    private void switchToRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchToRegisterButtonActionPerformed
        if (evt.getSource()==switchToRegisterButton) {
            loginPanel.setVisible(false);
            registerPanel.setVisible(true);
        }
    }//GEN-LAST:event_switchToRegisterButtonActionPerformed

    private void switchToLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchToLoginButtonActionPerformed
        if (evt.getSource()==switchToLoginButton) {
            loginPanel.setVisible(true);
            registerPanel.setVisible(false);
        }
    }//GEN-LAST:event_switchToLoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginConfirmButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPasswordInput;
    private javax.swing.JTextField loginUsernameInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerConfirmButton;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPasswordField registerPasswordConfirmInput;
    private javax.swing.JLabel registerPasswordConfirmLabel;
    private javax.swing.JPasswordField registerPasswordInput;
    private javax.swing.JLabel registerPasswordLabel;
    private javax.swing.JTextField registerUsernameInput;
    private javax.swing.JLabel registerUsernameLabel;
    private javax.swing.JButton switchToLoginButton;
    private javax.swing.JButton switchToRegisterButton;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
